name: Despliegue en AWS EC2

on:
  push:
    branches:
      - main

jobs:
  desplegar:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar clave SSH para conexión con la instancia
    - name: Configurar clave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    # 2. Verificar conexión SSH
    - name: Verificar conexión SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "echo 'Conexión SSH exitosa'"

    # 3. Instalar Git en la instancia EC2
    - name: Instalar Git en EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
          sudo apt-get update -y &&
          sudo apt-get install -y git
        "

    # 4. Clonar el repositorio si no existe
    - name: Clonar el repositorio
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
          if [ ! -d /home/${{ secrets.EC2_USER }}/app ]; then
            git clone https://github.com/GustavoAuger/desafio2 /home/${{ secrets.EC2_USER }}/app
          else
            echo 'El repositorio ya existe';
          fi
        "

    # 5. Instalar Python si no está presente
    - name: Instalar Python
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
          sudo apt-get update &&
          sudo apt-get install -y python3 python3-pip
        "

    # 6. Instalar dependencias desde requirements.txt
    - name: Instalar dependencias
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
          cd /home/${{ secrets.EC2_USER }}/app &&
          git fetch &&
          git diff --exit-code HEAD HEAD~1 requirements.txt || pip3 install --no-cache-dir -r requirements.txt
        "

    # 7. Actualizar la aplicación y reiniciarla
    - name: Actualizar la aplicación
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
          cd /home/${{ secrets.EC2_USER }}/app &&
          git pull &&
          nohup python3 app.py &
        "

    # 8. Validar el despliegue
    - name: Validar el despliegue
      run: |
        sleep 10
        curl -f http://${{ secrets.EC2_IP }} || exit 1
